### ISSUE TITLE
Add Plex

### ISSUE THREAD

**Issue by baconwaifu** [buraglio/broken-v6only#6]
Plex is "partial" in that it supports IPv6 at the socket-layer, but doesn't "auto-configure" IPv6 on the remote-end (the `[ipv4].[server-uid].plex.direct` system) so you need to manually create a hostname and appropriate DNS entries for it (which are sent up to plex.tv as additional hostnames to try) 

As for the 'uplink' connection to plex.tv/tvdb/etc, it should *probably* work with NAT64, but I haven't tested it as my network is dual-stack.

**Comment by buraglio** [comment]
added
